name: mapa_mrogowo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.10.2
  flutter_map: "^7.0.0"
  latlong2: "^0.9.1"
  google_maps_flutter: ^2.1.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true